### ISSUE TITLE
Assertion error in GAM._mask() method

### ISSUE THREAD

**Issue by jcreinhold** [dswah/pyGAM#174] opened 2018-06-13 19:42 UTC
Thank you for developing this package. I encountered the following error when using the gridsearch method on a PoissonGAM:

``` AssertionError: increase regularization ```

I was honestly fairly confused as to how to proceed and I tried changing nearly all the parameter settings in the gridsearch function as well as the instantiation of the PoissonGAM (in a way that seemed to make sense) to no avail. 

Could more description be added to this message to help users debug the issue?

FWIW, I am trying to use the PoissonGAM to do histogram smoothing, as described in the README. I have previously gotten it to work on very similar data, but the previously discussed error arises on this particular dataset. (If you have any notes on what I should do to correct this specific error, that help would be greatly appreciated).

Below is the full traceback (and some preceding RuntimeWarnings) generated when this AssertionError is raised. Thanks for the help.

```
/Users/jreinhold/Code/pyGAM/pygam/links.py:196: RuntimeWarning: overflow encountered in exp
  return np.exp(lp)
/Users/jreinhold/Code/pyGAM/pygam/pygam.py:941: RuntimeWarning: invalid value encountered in multiply
  self.distribution.V(mu=mu) *
/Users/jreinhold/Code/pyGAM/pygam/pygam.py:942: RuntimeWarning: divide by zero encountered in power
  weights ** -1)**-0.5)
/Users/jreinhold/Code/pyGAM/pygam/pygam.py:963: RuntimeWarning: invalid value encountered in greater_equal
  mask = (np.abs(weights) >= np.sqrt(EPS)) * np.isfinite(weights)
2018-06-13 15:27:32,417 - __main__ - ERROR - increase regularization
Traceback (most recent call last):
  File "/Users/jreinhold/Research/Prince/code/intensity-normalization/intensity_normalization/exec/ws-normalize", line 57, in main
    _ = whitestripe.ws_normalize(args.img_dir, args.contrast, args.mask_dir, args.output_dir)
  File "/Users/jreinhold/Research/Prince/code/intensity-normalization/intensity_normalization/normalize/whitestripe.py", line 94, in ws_normalize
    indices = whitestripe(img, contrast, mask=mask, verbose=verbose)
  File "/Users/jreinhold/Research/Prince/code/intensity-normalization/intensity_normalization/normalize/whitestripe.py", line 136, in whitestripe
    mode = get_last_mode(bins, counts, verbose=verbose)
  File "/Users/jreinhold/Research/Prince/code/intensity-normalization/intensity_normalization/normalize/whitestripe.py", line 207, in get_last_mode
    sh = smooth_hist(bins, counts, verbose=verbose)
  File "/Users/jreinhold/Research/Prince/code/intensity-normalization/intensity_normalization/normalize/whitestripe.py", line 250, in smooth_hist
    gam = PoissonGAM().gridsearch(bins, counts, progress=verbose)
  File "/Users/jreinhold/Code/pyGAM/pygam/pygam.py", line 3175, in gridsearch
    **param_grids)
  File "/Users/jreinhold/Code/pyGAM/pygam/pygam.py", line 2065, in gridsearch
    gam.fit(X, y, weights)
  File "/Users/jreinhold/Code/pyGAM/pygam/pygam.py", line 3067, in fit
    return super(PoissonGAM, self).fit(X, y, weights)
  File "/Users/jreinhold/Code/pyGAM/pygam/pygam.py", line 1220, in fit
    self._pirls(X, y, weights)
  File "/Users/jreinhold/Code/pyGAM/pygam/pygam.py", line 1031, in _pirls
    mask = self._mask(W.diagonal())
  File "/Users/jreinhold/Code/pyGAM/pygam/pygam.py", line 964, in _mask
    assert mask.sum() != 0, 'increase regularization'
AssertionError: increase regularization
```

**Comment by dswah** [comment] 2018-06-14 16:21
@jcreinhold I have also seen this error before, usually with the Poisson model, on specific datasets like you said.

I believe the problem is caused by a poor model initialization, which causes the second-order optimizer to overshoot the local minimum and go in an unfeasible direction.

A way to improve the initial model estimate is to solve a linear model, then use the result from that model as the starting point. 

Could you please try

```
# assuming you input and output data are X and y 
# lets let the optimizer run for 1 iteration, this way we can hack into the GAM machinery
gam = PoissonGAM(max_iter=1).fit(X, y)

# lets get the spline representation of the input data
M = gam._modelmat(X).A

# now transform the response data into a linear scale
ls = gam.link.link(y, gam.distribution)

# now lets solve the un-penalized least squares problem
a = M.T.dot(M)
b = M.T.dot(ls)
start = np.linalg.solve(a, b)

# put this solution as the starting point for the model
gam.coef_ = start

# raise the max iter
gam.max_iter = 50

# and continue solving the penalized GAM problem
gam.fit(X, y)
```

please let me know how this works...

**Comment by dswah** [comment] 2018-06-15 11:23
@jcreinhold i now realize that the code i gave you will work only in the best case scenario. 

let me make an esit.

**Comment by dswah** [comment] 2018-06-29 01:19
@jcreinhold sorry for the long delay.
i wrote a new version of pyGAM with the improved model initialization i described above.

could you upgrade your pyGAM version and try your code again?
( `pip install -U pygam`)

you should see v0.5.3.

**Comment by dswah** [comment] 2018-07-05 09:44
@jcreinhold i'm going to close this is issue for now since it seems that this is fixed..
please open it again if it's still an issue.

**Closed by dswah** 2018-07-05 09:44 UTC
